Importing All necessary Libraries to analyze the data

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("retail_demand_dataset.csv")

In [3]:
df.head()

,Date,Year,Month,Month_Name,Product,Store,Price,Competitor_Price,Discount_Percent,Marketing_Spend,Inventory_Level,Customer_Rating,Season,Demand
0,2022-01-01,2022,1,January,Laptop,Reliance Smart,44348.24,43743.59,4,69589.77,773,4.376166,Winter,773
1,2022-01-01,2022,1,January,Headphones,Spencer's,11008.59,11142.77,29,38682.24,770,3.401812,Winter,770
2,2022-01-01,2022,1,January,Smartwatch,More Supermarket,17690.70,18308.28,22,8365.57,1342,4.658020,Winter,396
3,2022-01-01,2022,1,January,Smartwatch,DMart,7739.33,7687.37,31,8566.47,979,3.662461,Winter,400
4,2022-01-01,2022,1,January,Tablet,More Supermarket,26754.99,26034.86,16,53178.40,591,4.555681,Winter,591

In [5]:
df.columns

Index(['Date', 'Year', 'Month', 'Month_Name', 'Product', 'Store', 'Price',
       'Competitor_Price', 'Discount_Percent', 'Marketing_Spend',
       'Inventory_Level', 'Customer_Rating', 'Season', 'Demand'],
      dtype='str')

In [6]:
df.shape

(50000, 14)

In [7]:
df.nunique()

Date                 1461
Year                    4
Month                  12
Month_Name             12
Product                 5
Store                   6
Price               49837
Competitor_Price    49855
Discount_Percent       41
Marketing_Spend     49851
Inventory_Level      1500
Customer_Rating     47650
Season                  4
Demand               1839
dtype: int64

In [8]:
df.isnull().sum()

Date                0
Year                0
Month               0
Month_Name          0
Product             0
Store               0
Price               0
Competitor_Price    0
Discount_Percent    0
Marketing_Spend     0
Inventory_Level     0
Customer_Rating     0
Season              0
Demand              0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe(include =object)

C:\Users\USER\AppData\Local\Temp\ipykernel_20760\2308160983.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include =object)

              Date Month_Name     Product  Store  Season
count        50000      50000       50000  50000   50000
unique        1461         12           5      6       4
top     2023-05-29     August  Smartwatch  DMart  Summer
freq            58       4347       10169   8422   12665